# Site settings
title: 39M 
email: 39M@outlook.com
description: ""
baseurl: ""
url: "http://39m.github.io/jekyll/"
img_url: http://39m.github.io/jekyll/assets/image
github_username: 39M

# Build settings
markdown: kramdown
permalink: pretty
